@host = http://localhost
@port = 5026
@RestaurantsAPI = {{host}}:{{port}}
@restaurantId = 5a06b102-b6dc-466b-7489-08ddd4dbe6cb
@token = 

GET {{RestaurantsAPI}}/api/restaurants
Accept: application/json

###

GET {{RestaurantsAPI}}/api/restaurants/{{restaurantId}}
Accept: application/json

###

POST {{RestaurantsAPI}}/api/restaurants
Content-Type: application/json

{
    "Name": "Gino's",
    "Description": "A culinary experience like no other",
    "Category": "Italian",
    "HasDelivery": true,
    "ContactEmail": "info@gourmetdelights.com",
    "ContactNumber": "555-123-4567",
    "City": "Metropolis",
    "Street": "456 Gourmet Avenue",
    "PostalCode": "54-323"
}

###

DELETE {{RestaurantsAPI}}/api/restaurants/{{restaurantId}}
Accept: application/json

###

PATCH {{RestaurantsAPI}}/api/restaurants/{{restaurantId}}
Content-Type: application/json

{
    "Name": "Gino's Updated",
    "Description": "A culinary experience like no other",
    "HasDelivery": false
}

###

POST {{RestaurantsAPI}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
    "Name": "Bolognese",
    "Description": "With tomato sauce and meat",
    "Price": 13.99,
    "KiloCalories": 450
}

###

GET {{RestaurantsAPI}}/api/restaurants/{{restaurantId}}/dishes
Accept: application/json

###

GET {{RestaurantsAPI}}/api/restaurants/{{restaurantId}}/dishes/3
Accept: application/json

###

DELETE {{RestaurantsAPI}}/api/restaurants/{{restaurantId}}/dishes
Accept: application/json

###

POST {{RestaurantsAPI}}/api/identity/register
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "MyP@ssword123"
}

###

POST {{RestaurantsAPI}}/api/identity/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "MyP@ssword123"
}

###

PATCH {{RestaurantsAPI}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "DateOfBirth": "2001-05-29",
    "Nationality": "Argentinian"
}

###

POST {{RestaurantsAPI}}/api/identity/user-role
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "UserEmail": "testuser@test.com",
    "RoleName": "Owner"
}

###

DELETE {{RestaurantsAPI}}/api/identity/user-role
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "UserEmail": "testuser@test.com",
    "RoleName": "Owner"
}