@host = http://localhost
@port = 5026
@RestaurantsAPI = {{host}}:{{port}}
@restaurantId = 85567a11-14ab-4f8a-a02d-08ddd419a811

GET {{RestaurantsAPI}}/api/restaurants
Accept: application/json

###

GET {{RestaurantsAPI}}/api/restaurants/{{restaurantId}}
Accept: application/json

###

POST {{RestaurantsAPI}}/api/restaurants
Content-Type: application/json

{
    "Name": "Spicy Delights Part",
    "Description": "A culinary experience like no other",
    "Category": "Fine Dining",
    "HasDelivery": true,
    "ContactEmail": "info@gourmetdelights.com",
    "ContactNumber": "555-123-4567",
    "City": "Metropolis",
    "Street": "456 Gourmet Avenue",
    "PostalCode": "54321"
}
